### ISSUE TITLE
how to increase ulimit stack

### ISSUE THREAD

**Issue by verdimrc** [NVIDIA/pyxis#126]
How to configure pyxis to match the --ulimit stack=xxx from docker run below?

```bash
docker run --gpus all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -it --rm nvcr.io/ea-bignlp/nemofw-training:23.07-py3 /bin/bash
```

**Comment by flx42** [comment]
Hi,

There should be no difference between the `ulimits` applied with or without pyxis in a Slurm job, thus you need to look into the Slurm mechanisms that set the job ulimits: https://slurm.schedmd.com/slurm.conf.html#OPT_PropagateResourceLimits

If you are able to change ulimits inside for all Slurm allocations / job steps, then pyxis will also get the ulimits.

For quick testing, if your `PropagateResourceLimits` settings allow it, you should be able to change the ulimits just for your current job:
```console
$ salloc -N1

$ ulimit -s ; srun --container-image ubuntu:22.04 bash -c 'ulimit -s'
8192
pyxis: importing docker image: ubuntu:22.04
pyxis: imported docker image: ubuntu:22.04
8192

$ ulimit -s 67108864
$ ulimit -s ; srun --container-image ubuntu:22.04 bash -c 'ulimit -s'
67108864
pyxis: importing docker image: ubuntu:22.04
pyxis: imported docker image: ubuntu:22.04
67108864
```

Also note that the `stack` ulimit might not be needed in all cases, it should only be set if you are facing crashes like `Segmentation Fault`, indicating a stack overflow due to a deep call stack, and that's not the case for most applications.

**Comment by verdimrc** [comment]
Thank you for your explanation!
