### ISSUE TITLE
How to set ENROOT_SQUASH_OPTIONS for --container-save

### ISSUE THREAD

**Issue by jfolz** [NVIDIA/pyxis#50]
Is there a way to set `ENROOT_SQUASH_OPTIONS` from `srun`?

At least this doesn't do the trick and `compressed.sqsh` ends up the same size as `uncompressed.sqsh`:

```
srun --container-image=uncompressed.sqsh \
     --container-save=compressed.sqsh \
     --export="ENROOT_SQUASH_OPTIONS=-comp lz4 -Xhc -b 262144" \
     echo done
```

**Comment by flx42** [comment]
Not right now, but it will be possible with PR https://github.com/NVIDIA/pyxis/pull/48, if you want to test it.
The background for this change is discussed in issue https://github.com/NVIDIA/pyxis/issues/46

(also, `--export="ENROOT_SQUASH_OPTIONS=-comp lz4 -Xhc -b 262144"` might not be what you want, since it sets `ENROOT_SQUASH_OPTIONS` but unsets all the other environment variables).

**Comment by jfolz** [comment]
I see, thanks! Don't think I can test #48 without breaking lots of things, but I assume we can put some sensible settings in `enroot.conf` and it will respect those?

**Comment by flx42** [comment]
> I assume we can put some sensible settings in enroot.conf and it will respect those?

Yes, absolutely. If it doesn't then it's a bug :)

**Comment by flx42** [comment]
Closing for now, please reopen if you see any issue after putting settings in `enroot.conf`
