### ISSUE TITLE
Support for sbatch

### ISSUE THREAD

**Issue by dr-br** [NVIDIA/pyxis#55]
We intend to use enroot for providing containerized Jupyter environments.
[batchspawner for Jupyterhub](https://github.com/jupyterhub/batchspawner) relies on the usage of sbatch.

Would it be possible to add the pyxis functionalities also to sbatch? Or is there a known workaround?

Thanks and best regards from Karlsruhe! ;)

**Comment by flx42** [comment]
Hello @dr-br, 

Do you intend to use `srun` within the containerized sbatch?
If yes, then it is a little bit tricky to enable proper Slurm support inside the pyxis container, see https://github.com/NVIDIA/pyxis/issues/31

If not, then it should be easier to enable but I suppose it would only make sense for single node jobs.

**Comment by dr-br** [comment]
Dear Felix,
no, `sbatch` is run natively on the host. We are currently investigating, how to use `srun` with `batchspawner` instead of `sbatch`, up to now, without success (even for non-containerized Jupyter Labs).

 Primary focus is single node at the moment.

**Comment by flx42** [comment]
@dr-br could you try the following branch? https://github.com/NVIDIA/pyxis/tree/2021-08-06/sbatch-salloc-support
It enables all the pyxis arguments for salloc and sbatch.

# sbatch
You might need to edit the [pyxis plugstack config](https://github.com/NVIDIA/pyxis/wiki/Setup#slurm-plugstack-configuration) if you are not using the default value for `SlurmSpoolDir` in `slurm.conf`. The default is the following:
```console
$ scontrol show config | grep Spool
SlurmdSpoolDir          = /var/spool/slurmd
```
If you use a different path, you will need to use the new plugstack option to override the path, for example: 
```console
$ cat /etc/slurm/plugstack.conf.d/pyxis.conf 
required /usr/local/lib/slurm/spank_pyxis.so slurmd_spool_dir=/var/run/slurmd
```
This is required because we can't query the Slurm configuration from a SPANK plugin (I will open an RFE against Slurm for this).

# salloc
Support for `salloc` comes for "free". But the behavior depends on the slurm configuration you use, if you use `LaunchParameters=use_interactive_step`, then you will immediately land inside the container:
```console
$ salloc --container-image=ubuntu:18.04 --no-container-mount-home
salloc: Granted job allocation 292
pyxis: importing docker image ...

root@node-1:/# grep PRETTY /etc/os-release 
PRETTY_NAME="Ubuntu 18.04.5 LTS"
```
Without `use_interactive_step`, the container arguments will be applied to the first srun:
```console
$ salloc --container-image=ubuntu:18.04 --no-container-mount-home
salloc: Granted job allocation 293

$ grep PRETTY /etc/os-release 
PRETTY_NAME="Ubuntu 21.04"

$ srun --pty bash
pyxis: importing docker image ...

root@ioctl:/# grep PRETTY /etc/os-release 
PRETTY_NAME="Ubuntu 18.04.5 LTS"
```

# multi-node
As I mentioned above, it's tricky to use a containerized multi-node sbatch (as you have to go to great lengths to enable `srun` inside your container), but the current patch is not trying to prevent this from happening.

**Comment by flx42** [comment]
And here is a run.sub example:
```bash
#!/bin/bash -eux
#SBATCH --container-image ubuntu:18.04

grep PRETTY /etc/os-release
```

Usage:
```console
$ sbatch run.sub 
Submitted batch job 294

$ cat slurm-294.out 
pyxis: importing docker image ...
+ grep PRETTY /etc/os-release
PRETTY_NAME="Ubuntu 18.04.5 LTS"
```

**Comment by flx42** [comment]
Actually, please try v2 of the branch instead, on this branch: https://github.com/NVIDIA/pyxis/tree/2021-08-06/sbatch-salloc-support-v2

It will avoid the need to specify the spool dir, as it will only bind mount the sbatch script and now the whole dir.

**Comment by dr-br** [comment]
We will try and give you feedback ASAP.
Thanks a lot!

**Comment by dr-br** [comment]
Feedback:
Works as expected :)
We got JupyterHub + batchspawner to start containerized JupyterLab images.

Will this feature be mainlined?

Thanks a lot
Samuel

**Comment by flx42** [comment]
Yes, it will be mainlined, I'll do a bit more testing and push to the main branch.

**Comment by flx42** [comment]
Pushed in this commit: https://github.com/NVIDIA/pyxis/commit/68333337b8e198e9c720b626c890a27f62c60645
The only difference with the `2021-08-06/sbatch-salloc-support-v2` is that admins will be able to disable support for sbatch/salloc in the plugstack configuration file, in case there are concerns about users running multi-node containerized sbatch jobs and being confused. By default it is enabled so it should work for your use case.

This is not part of a pyxis release yet.
