### ISSUE TITLE
Should `--no-container-remap-root` be equivalent to `ENROOT_REMAP_ROOT no` ?

### ISSUE THREAD

**Issue by vfdev-5** [NVIDIA/pyxis#64]
Question:
if we set in `enroot.conf` : `ENROOT_REMAP_ROOT   no` should it be equivalent to `--no-container-remap-root` option in pyxis and if we call:
```bash
srun  --container-image=mycontainer.sqsh whoami
> user
```
and the same as 
```bash
srun  --container-image=mycontainer.sqsh --no-container-remap-root whoami
> user
```
?

Currently (on master), this is not true:
```
srun  --container-image=mycontainer.sqsh whoami
> root
```
and
```bash
srun  --container-image=mycontainer.sqsh --no-container-remap-root whoami
> user
```

Thanks

**Comment by flx42** [comment]
Good catch, it used to be that pyxis had a different code path internally depending on whether root remapping needed to be done, and there was no way to query the enroot config so that's why there is `remap_root` in the pyxis configuration file.

But this should not be needed anymore, pyxis should now be able to just use the enroot default when `--container-remap-root` and `--no-container-remap-root` are not set. I will make the change.

**Comment by flx42** [comment]
Should work fine now, please test if you can :)
